
export default {
  index: '/member/index',
  member: '/member',
  address: '/member/memberaddress',
  defaultAddress: '/member/memberaddress/default',
  auth: '/member/memberauth',
  auths: '/member/memberauths',
  thirdAuth: '/member/third/memberauth',
  authUsable: '/member/memberauth/usable',
  password: '/member/password',
  sendbindemail: '/member/sendbindemail',
  redEnvelope: '/member/couponplatforms',
  coupon: '/member/coupons',
  other: '/promotion/couponthirdusers/member',
  collectionProduct: '/member/membercollectionproducts',
  collectionSeller: '/member/membercollectionsellers',
  isCollectionProduct: '/member/membercollectionproducts/collection',
  isCollectionSeller: '/member/membercollectionsellers/collection',
  logs: '/member/productlooklogs',
  bindEmail: '/member/sendbindemail',
  upload: '/member/memberauth/imgupload',
}