export const ICON_MAP = {
  edit: require('@/assets/images/icons/edit.png'),
  shop: require('@/assets/images/icons/shop.png'),
  store: require('@/assets/images/icons/store.png'),
  arrow: require('@/assets/images/icons/arrow.png'),
  delete: require('@/assets/images/icons/delete.png'),
  setting: require('@/assets/images/icons/setting.png'),
  warning: require('@/assets/images/icons/warning.png'),
  messageWhite: require('@/assets/images/icons/message-white.png'),
  closedNotice: require('@/assets/images/icons/closed-notice.png'),
  exclamation: require('@/assets/images/icons/exclamation.png'),
  deleteOutlined: require('@/assets/images/icons/delete-outlined.png'),
  refund: require('@/assets/images/icons/refund.png'),
  return: require('@/assets/images/icons/return.png'),
  barter: require('@/assets/images/icons/barter.png'),
  appeal: require('@/assets/images/icons/appeal.png'),
  radio: require('@/assets/images/icons/checkbox.png'),
  radioChecked: require('@/assets/images/icons/checkbox-checked.png'),
  star: require('@/assets/images/icons/star.png'),
  starGrey: require('@/assets/images/icons/star-grey.png'),
  category: require('@/assets/images/icons/category.png'),
  customerServiceGray: require('@/assets/images/icons/customer-service-gray.png')
}